name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region eu-north-1 \
          | docker login --username AWS --password-stdin 191369739072.dkr.ecr.eu-north-1.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t my-nginx-app .

      - name: Tag image
        run: |
          docker tag my-nginx-app:latest 191369739072.dkr.ecr.eu-north-1.amazonaws.com/my-nginx-app:latest

      - name: Push image
        run: |
          docker push 191369739072.dkr.ecr.eu-north-1.amazonaws.com/my-nginx-app:latest

      - name: Force ECS deployment
        run: |
          aws ecs update-service \
            --cluster devops-cluster \
            --service nginx-service-lb \
            --force-new-deployment

      - name: Wait for ECS deployment
        run: |
          for i in {1..40}; do
            STATUS=$(aws ecs describe-services \
              --cluster devops-cluster \
              --services nginx-service-lb \
              --query "services[0].deployments[?status=='PRIMARY'].rolloutState" \
              --output text)

            echo "Current rollout state: $STATUS"

            if [ "$STATUS" = "COMPLETED" ]; then
              echo "Deployment successful"
              exit 0
            fi

            if [ "$STATUS" = "FAILED" ]; then
              echo "Deployment failed"
              exit 1
            fi

            sleep 15
          done

          echo "Timed out waiting for deployment"
          exit 1