name: Deploy to ASG

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Start Instance Refresh
        id: refresh
        run: |
            REFRESH_ID=$(aws autoscaling start-instance-refresh \
            --auto-scaling-group-name devops-asg \
            --query 'InstanceRefreshId' \
            --output text)

            echo "REFRESH_ID=$REFRESH_ID" >> $GITHUB_ENV

      - name: Wait for Instance Refresh to Complete
        run: |
            echo "Waiting for instance refresh to complete..."

            while true; do
                STATUS=$(aws autoscaling describe-instance-refreshes \
                    --auto-scaling-group-name devops-asg \
                    --query "InstanceRefreshes[0].Status" \
                    --output text)

                echo "Current status: $STATUS"

                if [ "$STATUS" = "Successful" ]; then
                    echo "Deployment successful"
                    break
                fi

                if [ "$STATUS" = "Failed" ] || [ "$STATUS" = "Cancelled" ]; then
                    echo "Deployment failed"
                    exit 1
                fi

                sleep 20
            done

      - name: Check final deployment status
        run: |
            STATUS=$(aws autoscaling describe-instance-refreshes \
                --auto-scaling-group-name devops-asg \
                --query "InstanceRefreshes[0].Status" \
                --output text)

            echo "Final status: $STATUS"

            if [ "$STATUS" = "Failed" ] || [ "$STATUS" = "Cancelled" ]; then
                echo "Deployment failed — triggering rollback"
                exit 1
            fi
